spring:
  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    host: ${RABBIT_HOST}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cloud:
    function:
      definition: personEventListener
    stream:
      bindings:
        personEventListener-in-0:
          destination: persons.topic
          group: account-service-consumer
        persons-event-output:
          destination: persons.topic
  data:
    rest:
      basePath: /api
  application:
    name: account-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true

